"""add chat_id to tts_requests

Revision ID: 37a46b18bcfb
Revises: 8c0c7d1a34c5
Create Date: 2026-02-28 15:17:36.031393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37a46b18bcfb'
down_revision: Union[str, Sequence[str], None] = '8c0c7d1a34c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tts_requests', sa.Column('chat_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'tts_requests', 'chats', ['chat_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tts_requests', type_='foreignkey')
    op.drop_column('tts_requests', 'chat_id')
    # ### end Alembic commands ###
